Library/Models/AuthBookPublish.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Library.Models
{
    public class AuthBookPublish
    {
        public Author author { get; set; }
        public Book book { get; set; }
        public Publisher publisher { get; set; }
    }
}

Library/Models/Author.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Library.Models
{
    public class Author
    {
        public int id { get; set; }

        //[Required(ErrorMessage = "Введите имя автора")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Введите дату рождения автора")]
        public DateTime DateBirth { get; set; }
        public DateTime ? DateOfDeath { get; set; }

        public List<Author> listOfAuthors = new List<Author>();
        public void AddAuthor(Author author)
        {
            author.id = (listOfAuthors.Any() ? listOfAuthors.Max(i => i.id) : 0) + 1;
            listOfAuthors.Add(author);
        }

        public void DelAuthor(int id, Book book)
        {
            int count = listOfAuthors.Count();

            foreach (var item in listOfAuthors)
            {
                if (id == item.id)
                {
                    listOfAuthors.Remove(item);
                    book.DeleteBookOfAuthor(id);
                    break;
                }
            }

        }
        public Author GetAuthor(string AuthorDropList)
        {
            foreach (var item in listOfAuthors)
            {
                if (item.Name == AuthorDropList)
                {
                    return item;
                }
            }
            return null;
        }


    }
}

Library/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class Book
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public Publisher Publisher { get; set; }

        //public IEnumerable<Author> Authors;

        public Author AuthorBook { get; set; }

        [Required(ErrorMessage = "Введите дату выпуска")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Введите число страниц")]
        public int PageCount { get; set; }

        [Required(ErrorMessage = "Введите ISBN")]
        public string ISBN { get; set; }

        public List<Book> books = new List<Book>();

        public Book()
        {
            if(AuthorBook==null)
            AuthorBook = new Author();
        }

        public void AddBook(Book book, Author authors, Publisher publisher)
        {

            book.Id = (books.Any() ? books.Max(i => i.Id) : 0) + 1;

            foreach (var item in authors.listOfAuthors)
            {

                if (item.id == book.AuthorBook.id)
                {
                    book.AuthorBook = item;
                }

            }
            foreach (var item in publisher.MyPublishers)
            {
                if (item.id == book.Publisher.id)
                {
                    book.Publisher = item;
                }
            }

            books.Add(book);
        }
      
        public void DeleteBook(int BookId)
        {
            for(int i=0;i<books.Count();i++)
            {
                if(BookId==books[i].Id)
                {
                    books.Remove(books[i]);
                    //i = 0;
                    DeleteBook(BookId);
                }
            }
        }

        public void DeleteBookOfAuthor(int AuthorId)
        {
            for (int i = 0; i < books.Count(); i++)
            {
                if (AuthorId == books[i].AuthorBook.id)
                {
                    books.Remove(books[i]);
                    //i = 0;
                    DeleteBookOfAuthor(AuthorId);
                }
            }
        }

    }
}

Library/Models/Publisher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Library.Models
{
    public class Publisher
    {
        public int id { get; set; }

        //[Required(ErrorMessage = "Ввведите название типографии")]
        public string Name { get; set; }

        public List<Publisher> MyPublishers = new List<Publisher>();

        public void AddPublisher(Publisher publisher)
        {
            publisher.id = (MyPublishers.Any() ? MyPublishers.Max(i => i.id) : 0) + 1;
            MyPublishers.Add(publisher);
        }

        public void DeletePublisher(string publisher)
        {
            foreach(var item in MyPublishers)
            {
                if (item.Name == publisher)
                {
                    MyPublishers.Remove(item);
                    break;
                }
            }
        }


    }
}

Library/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Library/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Library.Models;

namespace Library.Controllers
{
    public class PublisherController : Controller
    {
        // GET: Publisher

        static Publisher publisher = new Publisher();

        static Author authors = new Author();

        static Book book = new Book();

        static List<SelectListItem> mylist;

        static List<SelectListItem> mylistPublish;
        public ActionResult Index()
        {
            AllViewBag();

            return View();
        }

        public ActionResult DelIndex(string delpublisher)
        {
            publisher.DeletePublisher(delpublisher);

            AllViewBag();

            return RedirectToAction("Index");
        }

        public ActionResult DelAuthor(int id)
        {
            authors.DelAuthor(id, book);

            AllViewBag();


            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult IndexPublisher(AuthBookPublish model)
        {
            if(ModelState.IsValid)
            {
                publisher.AddPublisher(model.publisher);
                AllViewBag();
                return View("Index");
            }
            else
            {
                AllViewBag();
                return View("Index");
            }
        }

        [HttpPost]
        public ActionResult IndexAuthor(AuthBookPublish model)
        {
            if(ModelState.IsValid)
            {
                authors.AddAuthor(model.author);
                AllViewBag();
                return View("Index");
            }
            else
            {
                AllViewBag();
                return View("Index");
            }

        }

        [HttpPost]
        public ActionResult IndexBook(AuthBookPublish model, FormCollection form)
        {
            if(ModelState.IsValid)
            {
                //string strDDL = form["NameAuthor"].ToString();
                //string strDDLPublish = form["NamePublish"].ToString();
                book.AddBook(model.book, authors, publisher);
                //book.AddBook(model.book, strDDL, strDDLPublish, authors, publisher);
                AllViewBag();

                return View("Index");
            }

            else
            {
                AllViewBag();

                return View("Index");
            }
        }

        public ActionResult DelBook(int id)
        {
            book.DeleteBook(id);

            AllViewBag();

            return View("Index");
        }

        public void AllViewBag()
        {
            ViewBag.ListPublisher = publisher.MyPublishers;
            ViewBag.ListAuthors = authors.listOfAuthors;
            ViewBag.Books = book.books;

                mylist = new List<SelectListItem>();
                for (int i = 0; i < authors.listOfAuthors.Count(); i++)
                    mylist.Add(new SelectListItem { Text = authors.listOfAuthors[i].Name, Value = authors.listOfAuthors[i].id.ToString() });

            mylistPublish = new List<SelectListItem>();
            for (int i = 0; i < publisher.MyPublishers.Count(); i++)
                mylistPublish.Add(new SelectListItem { Text = publisher.MyPublishers[i].Name, Value = publisher.MyPublishers[i].id.ToString() });

            ViewBag.ListPublishSelect = mylistPublish;
            ViewBag.listSelect = mylist;
            ViewBag.listBooks = book.books;
        }
    }
}

Library/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h2>@Html.ActionLink("Вход в библиотеку", "Index", "Publisher", null, null)</h2>
    </div>
</body>
</html>

Library/Views/Publisher/Index.cshtml
@model Library.Models.AuthBookPublish
@{
    Layout = null;
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link type="text/css" rel="stylesheet" href="../../Content/Site.css" />
    <title>Publisher</title>
</head>
<body>
    <h1 class="bibl">Библиотека</h1>
    <div class="mainblock">
        @Html.ValidationSummary()
        <div class="mybloks">
            <h2 class="addbook">Добавление Типографии</h2>
            @using (Html.BeginForm("IndexPublisher", "Publisher", FormMethod.Post))
            {
                <div class="textbloks"><p>Типография: </p></div><p> @Html.TextBoxFor(x => x.publisher.Name, new { @class = "textbloks2" })</p>
                <div class="textbloks"><input type="submit" value="Отправить" /></div>
            }
        </div>
        <div class="mybloks">
            <h2 class="addbook">Добавление Авторов</h2>

            @using (Html.BeginForm("IndexAuthor", "Publisher", FormMethod.Post))
            {
                <div class="textbloks"><p>Имя:</p></div><p> @Html.TextBoxFor(x => x.author.Name, new { @class = "textbloks2" })</p>
                <div class="textbloks"><p>Дата рождения:</p></div><p> @Html.TextBoxFor(x => x.author.DateBirth, new { @class = "textbloks2" })</p>
                <div class="textbloks"><p>Дата смерти:</p></div><p> @Html.TextBoxFor(x => x.author.DateOfDeath, new { @class = "textbloks2" })</p>
                <div class="textbloks"><input type="submit" value="Отправить" /></div>

            }
        </div>
        <div class="mybloks">
            <h2 class="addbook">Добавление книг</h2>
            @using (Html.BeginForm("IndexBook", "Publisher", FormMethod.Post))
            {     
                <div class="textbloks"><p>Название:</p></div><div class="textbloks2"><p> @Html.TextBoxFor(x => x.book.Name)</p></div>

                <div class="textbloks"><p>Дата публикации: </p></div><div class="textbloks2"><p> @Html.TextBoxFor(x => x.book.Date)</p></div>

                <div class="textbloks"><p>Число страниц:</p></div><div class="textbloks2"><p> @Html.TextBoxFor(x => x.book.PageCount)</p></div>

                <div class="textbloks"><p>ISBN:</p></div><div class="textbloks2"><p> @Html.TextBoxFor(x => x.book.ISBN)</p></div>

                <div class="textbloks"><p>Автор:</p></div><div class="textbloks2"><p> @Html.DropDownListFor(x => x.book.AuthorBook.id, new SelectList(ViewBag.listSelect, "Value", "Text"), "-Select-")</p></div>
 
                <div class="textbloks"><p>Типография:</p></div><div class="textbloks2"><p> @Html.DropDownListFor(x => x.book.Publisher.id, new SelectList(ViewBag.ListPublishSelect, "Value", "Text"), "-Select-")</p></div>
                @Html.ValidationMessageFor(x=>x.book.Publisher.id)
                <div class="textbloks"><input type="submit" value="Отправить" /></div>
            }
        </div>
    </div>



    <div class="lists">
        <h2>Список Типографий:</h2>
        @if (ViewBag.ListPublisher.Count > 0)
        {
            foreach (var item in ViewBag.ListPublisher)
            {
                <p>@item.Name | @Html.ActionLink("Удалить", "DelIndex", "Publisher", new { delpublisher = item.Name }, null)</p>
            }
        }
        <h2>Список Авторов:</h2>
        @if (ViewBag.ListAuthors.Count > 0)
        {
            foreach (var item in ViewBag.ListAuthors)
            {
                <p>id: @item.id</p>
                <p>Имя: @item.Name | @Html.ActionLink("Удалить", "DelAuthor", "Publisher", new { id = item.id }, null)</p>
                        <p>Дата Рождения: @item.DateBirth</p>
                        <p>Дата Смерти: @item.DateOfDeath</p>
                        <p>======================================</p>
            }
        }

        <h2>Список Книг:</h2>
        @if (ViewBag.listBooks.Count > 0)
        {
            foreach (var item in ViewBag.listBooks)
            {
                <p>id: @item.Id</p>
                <p>Название: @item.Name | @Html.ActionLink("Удалить", "DelBook", "Publisher", new { id = item.Id }, null)</p>
                        <p>Автор: @item.AuthorBook.Name </p>
                        <p>Автор Id: @item.AuthorBook.id </p>
                        <p>Дата публикации:: @item.Date</p>
                        <p>Число страниц: @item.PageCount</p>
                        <p>Типография: @item.Publisher.Name</p>
                        <p>ISBN: @item.ISBN</p>
                        <p>===========================================</p>
            }
        }

    </div>
</body>
</html>

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>